FROM nginx:alpine

# Instalar openssl
RUN apk add --no-cache openssl

# Generar un certificado SSL autofirmado válido por 1 año
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout /etc/ssl/private/nginx-selfsigned.key \
    -out /etc/ssl/certs/nginx-selfsigned.crt \
    -subj "/C=ES/ST=Local/L=Local/O=Biblioteca/CN=localhost"
